epochs: 50
batch_size: 32
sequence_length: 7
hidden_dim: 128
learning_rate: 0.001
save_dir: checkpoints/5_checkpoints/
resume_from_checkpoint: '/DATA/Sonia/TrackTrack/project/checkpoints/epoch_43_train_loss_0.810430394708419_val_loss_0.3990452857105993.pth'  
